### ISSUE TITLE
Handling head metadata for SEO?

### ISSUE THREAD

**Issue by Sigmanificient** [coral-lang/Language-Design#4]
How would head be handle in coral?

Let say i have a head component:
```html
comp Head
<meta property="og:title" content="Lorem Ipsum ..." />
```
Having a this as would require you to use an even broader component to call that one in

```html
com HTML
<!DOCTYPE html>
<html>
  <Head />
  <Body />
</html>
```
But i believe this would cause problem for handling the meta tags properly
What happen to my stylesheet? Do i have to declare it within the `Head` component?
What about font or script link? About about js scripts within the `HTML` component?

I propose to use a new keyword for handling this problem:

```html
head BaseHead
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">

head CustomHead < BaseHead
<meta property="og:title" content="Lorem Ipsum ..." />
```

Using head would allow to not only avoid having a `HTML` component, but also to declare a component as head.
Coral can then understand it and replace to correct head elements, while adding whatever it need the the head.

Then, either do use in within a page by calling `<CustomHead/>` or it would take the head defined within the page?

**Comment by Arthurdw** [comment]
I really don't like this syntax and the way of implementing things. This issue is addressing a problem that currently has no solution yet. But we'll figure something out.

The general issue this is addressing is how is a response document defined and structured. I'll be closing this issue and making a PR in the following days to solve this problem.
